beautify

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -123,7 +123,10 @@ jobs:
 
           if [[ "$status" == *success* ]]; then
             echo "✅ Moodle update successful"
+            echo -e "\033[32m✅ Moodle update successful\033[0m"
           else
             echo "❌ Moodle API error: '$status'" >&2
+            echo -e "\033[31m❌ Moodle API error: '$status'\033[0m" >&2
+
             exit 1
           fi
