trying to detect moodle error

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -115,7 +115,6 @@ jobs:
             --data "feedback=$feedback" \
             --data "max=2" \
             --data "externallink=${{ github.repository }}")
-          echo "$response"
           
           # Extract the <VALUE> within KEY name="name"
           status=$(echo "$response" \
@@ -123,8 +122,8 @@ jobs:
             | tr -d '\r\n')
 
           if [[ "$status" == *success* ]]; then
-            echo "Moodle update successful"
+            echo "✅ Moodle update successful"
           else
-            echo "Moodle API error: '$status'" >&2
+            echo "❌ Moodle API error: '$status'" >&2
             exit 1
           fi
